export enum ADMIN_PAGE_CATEGORY {
  USERS_AND_ORGANIZATIONS = 'USERS_AND_ORGANIZATIONS',
  ACCESS_RIGHTS = 'ACCESS_RIGHTS',
  REFERENCE_DATA = 'REFERENCE_DATA',
  SYSTEM = 'SYSTEM',
  HELPERS = 'HELPERS',
}
